
// NOTE! Test generated by chatGPT!

using Application.Abstractions;
using Application.DTOs;
using Infrastructure.Data.Identity;
using Infrastructure.Services;
using Microsoft.AspNetCore.Identity;
using Moq;

namespace Tests.Infrastructure;

public class AuthenticationServiceTests
{

    // Mock UserManager, JwtTokenService and RefreshTokenService.
    private readonly Mock<UserManager<AppUser>> _userManager;
    private readonly Mock<IJwtTokenService> _jwt;
    private readonly Mock<IRefreshTokenService> _refresh;

    // Using the actual AuthenticationService.
    private readonly AuthenticationService _service;

    public AuthenticationServiceTests() 
    {
        _userManager = MockHelpers.MockUserManager();
        _jwt = new Mock<IJwtTokenService>();
        _refresh = new Mock<IRefreshTokenService>();

        // Creates the AuthenticationService dependencies.
        _service = new AuthenticationService(
            _userManager.Object,
            _jwt.Object,
            _refresh.Object
        );
    }

    [Fact]
    // Verifies that login fails when no user exists with the provided email.
    public async Task Login_ShouldFail_WhenUserNotFound()
    {
        _userManager
            .Setup(x => x.FindByEmailAsync(It.IsAny<string>())) // Simulates missing user in database.
            .ReturnsAsync((AppUser?)null);

        var result = await _service.LoginAsync(
            new LoginAuthRequest("test@test.com", "password"),
            null // No IpAddress.
        ); // Trying to login with an invalid email address and password.

        Assert.False(result.IsSuccess);
        Assert.Equal("Unauthorized", result.ErrorMessage);
    }

    [Fact]
    // Verifies that the login was successful when the credentials (email and password) are valid.
    public async Task Login_ShouldSucceed_WhenCredentialsAreValid()
    {
        var user = new AppUser
        {
            Id = "1",
            Email = "test@test.com"
        }; // Creates an object that represents a user.

        _userManager.Setup(x => x.FindByEmailAsync(It.IsAny<string>()))
                    .ReturnsAsync(user);

        _userManager.Setup(x => x.IsLockedOutAsync(user))
                    .ReturnsAsync(false);

        _userManager.Setup(x => x.CheckPasswordAsync(user, It.IsAny<string>()))
                    .ReturnsAsync(true);

        _userManager.Setup(x => x.GetRolesAsync(user))
                    .ReturnsAsync(new List<string> { "User" });

        _jwt.Setup(x => x.CreateAccessToken(user.Id, user.Email!, It.IsAny<IList<string>>()))
            .Returns(new AccessTokenResult("token", "bearer", 3600, DateTimeOffset.UtcNow)); // Mock a Access token to return.

        _refresh.Setup(x => x.CreateAsync(user.Id, It.IsAny<string>(), It.IsAny<CancellationToken>())) // Mock a Refresh token to return.
            .ReturnsAsync("refresh-token");

        var result = await _service.LoginAsync(
            new LoginAuthRequest("test@test.com", "password"),
            null // No IpAddress.
        );// Trying to login with an valid email address and password.

        Assert.True(result.IsSuccess);
        Assert.NotNull(result.Value);
        Assert.Equal("token", result.Value!.AccessToken.AccessToken);
        Assert.Equal("refresh-token", result.Value.RefreshToken);
    }

    [Fact]
    // Verifies that login fails when user is locked out.
    public async Task Login_ShouldFail_WhenUserIsLockedOut()
    {
        var user = new AppUser { Id = "1", Email = "test@test.com" }; // Creates an object that represents a user.

        _userManager.Setup(x => x.FindByEmailAsync(It.IsAny<string>()))
                    .ReturnsAsync(user);

        _userManager.Setup(x => x.IsLockedOutAsync(user))
                    .ReturnsAsync(true);

        var result = await _service.LoginAsync(
            new LoginAuthRequest("test@test.com", "password"),
            null
        );

        Assert.False(result.IsSuccess);
        Assert.Equal("User is temporarily locked out", result.ErrorMessage);
    }

    [Fact]
    // Verifies that login fails when password is invalid.
    public async Task Login_ShouldFail_WhenPasswordIsInvalid()
    {
        var user = new AppUser { Id = "1", Email = "test@test.com" };

        _userManager.Setup(x => x.FindByEmailAsync(It.IsAny<string>()))
                    .ReturnsAsync(user);

        _userManager.Setup(x => x.IsLockedOutAsync(user))
                    .ReturnsAsync(false);

        _userManager.Setup(x => x.CheckPasswordAsync(user, It.IsAny<string>()))
                    .ReturnsAsync(false);

        var result = await _service.LoginAsync(
            new LoginAuthRequest("test@test.com", "wrong"),
            null
        );

        Assert.False(result.IsSuccess);
        Assert.Equal("Unauthorized", result.ErrorMessage);

        _userManager.Verify(x => x.AccessFailedAsync(user), Times.Once); // Assert that the method is called exactly once. May trigger a lockout depending on configuration.
    }

    [Fact]
    // Verifies that registration succeeds when Identity confirms user creation.
    public async Task Register_ShouldSucceed_WhenUserIsCreated()
    {
        _userManager
            .Setup(x => x.CreateAsync(It.IsAny<AppUser>(), It.IsAny<string>()))
            .ReturnsAsync(IdentityResult.Success);

        var result = await _service.RegisterAsync(
            new RegisterAuthRequest("test@test.com", "Password123!")        
        );

        Assert.True(result.IsSuccess);
        Assert.NotNull(result.Value);
        Assert.Equal("test@test.com", result.Value!.Email); // Assert same email input as output.
    }

    [Fact]
    // Verify that registration fails when Identity denies user creation.
    public async Task Register_ShouldFail_WhenIdentityFails()
    {
        var errors = new IdentityError[]
        {
        new IdentityError { Code = "DuplicateEmail", Description = "Email already exists" }
        }; // simulates a result dictionary with errors. 

        _userManager.Setup(x => x.CreateAsync(It.IsAny<AppUser>(), It.IsAny<string>()))
                    .ReturnsAsync(IdentityResult.Failed(errors)); // Simulates user creation failing regardless of username or password input.

        var result = await _service.RegisterAsync(
            new RegisterAuthRequest("test@test.com", "Password123!")
        );

        Assert.False(result.IsSuccess);
        Assert.NotNull(result.errors);
        Assert.True(result.errors!.ContainsKey("DuplicateEmail")); // Assert same error message in output.
    }

    [Fact]
    // Verifies refresh of access token fails if refresh token is invalid.
    public async Task Refresh_ShouldFail_WhenTokenIsInvalid()
    {
        _refresh.Setup(x => x.RotateAsync(It.IsAny<string>(), It.IsAny<string>(), It.IsAny<CancellationToken>()))
                .ReturnsAsync(RotateRefreshTokenResult.Failed()); // Simulates fail to return new access token regardless of input.

        var result = await _service.RefreshAsync(
            new RefreshAuthRequest("bad-token"),
            null
        ); // Simulates a "bad-token" input.

        Assert.False(result.IsSuccess);
        Assert.Equal("Invalid refresh token.", result.ErrorMessage);
    }

    [Fact]
    // Verifies that a token update is not possible if the user does not exist.
    public async Task Refresh_ShouldFail_WhenUserDoesNotExist()
    {
        _refresh.Setup(x => x.RotateAsync(It.IsAny<string>(), It.IsAny<string>(), It.IsAny<CancellationToken>()))
                .ReturnsAsync(RotateRefreshTokenResult.Success("1", "new-token")); // Simulates the return of a new valid token.

        _userManager.Setup(x => x.FindByIdAsync("1"))
                    .ReturnsAsync((AppUser?)null); // Simulates that a user is not in the system.

        var result = await _service.RefreshAsync(
            new RefreshAuthRequest("token"),
            null
        ); // Trying to refresh the access token for a non existing user.

        Assert.False(result.IsSuccess);
        Assert.Equal("User not found", result.ErrorMessage);
    }

    [Fact]
    // Verifies that the method to get user information fails if a userId is not provided.
    public async Task GetCurrentUser_ShouldFail_WhenUserIdIsEmpty()
    {
        var result = await _service.GetCurrentUserAsync("");

        Assert.False(result.IsSuccess);
        Assert.Equal("Unauthorized", result.ErrorMessage);
    }

    [Fact]
    // Verify that the method fails if the user does not exist in the database.
    public async Task GetCurrentUser_ShouldFail_WhenUserNotFound()
    {
        _userManager.Setup(x => x.FindByIdAsync(It.IsAny<string>()))
                    .ReturnsAsync((AppUser?)null); // Returns null regardless of input.

        var result = await _service.GetCurrentUserAsync("1");

        Assert.False(result.IsSuccess);
        Assert.Equal("Unauthorized", result.ErrorMessage);
    }

    [Fact]
    // Verifies that new tokens (access and refresh tokens) are returned if success.
    public async Task Refresh_ShouldSucceed_WhenTokenIsValid()
    {
        _refresh.Setup(x => x.RotateAsync(It.IsAny<string>(), It.IsAny<string>(), It.IsAny<CancellationToken>()))
                .ReturnsAsync(RotateRefreshTokenResult.Success("1", "new-token"));

        var user = new AppUser { Id = "1", Email = "test@test.com" };

        _userManager.Setup(x => x.FindByIdAsync("1"))
                    .ReturnsAsync(user);

        _userManager.Setup(x => x.GetRolesAsync(user))
                    .ReturnsAsync(new List<string> { "User" });

        _jwt.Setup(x => x.CreateAccessToken(user.Id, user.Email!, It.IsAny<IList<string>>()))
            .Returns(new AccessTokenResult("access", "bearer", 3600, DateTimeOffset.UtcNow));

        var result = await _service.RefreshAsync(
            new RefreshAuthRequest("token"),
            null
        );

        Assert.True(result.IsSuccess);
        Assert.Equal("new-token", result.Value!.RefreshToken);
    }
}
